version: '3'
services:
  app-fibonacci:
    container_name: full_app
    build: .
    ports:
      - 8080:8080
      - 4040:4040
    restart: on-failure
    depends_on:
      - redis-app

  redis-app:
    image: "redis:alpine"
    ports:
      - 6379:6379
    volumes:
      - redis-data:/var/lib/redis
      - redis.conf:/usr/local/etc/redis/redis.conf
    restart: on-failure

volumes:
  redis-data:
  redis.conf:

